Repository WildCodeSchool/lyon-js-sept2020-p3-oufgarden-front-office, pull requests merged in 2021-01, with the labels that each got.

#4 User feed like
  package-lock.json
  package.json
  src/components/App.js
  src/components/ArticlesDetails.js
  src/components/Contexts/UserContextProvider.js
  src/components/Feed.js
  src/components/Login.js
  src/components/Navbar.js
  src/components/UserContext.js
  src/components/style/ArticlesDetails.scss
  src/components/style/Feed.scss
  src/components/style/Login.scss
  src/components/style/Navbar.scss
  src/history.js
  src/images/black_logo.png
Labels: Ready for Validation

#8 Comment
  package-lock.json
  package.json
  src/components/App.js
  src/components/ArticlesDetails.js
  src/components/Comment.js
  src/components/CommentForm.js
  src/components/CommentList.js
  src/components/Feed.js
  src/components/Login.js
  src/components/style/ArticlesDetails.scss
  src/components/style/Comment.scss
  src/components/style/CommentForm.scss
  src/components/style/CommentList.scss
  src/components/style/Feed.scss
  src/images/Fichier 1.png
  src/images/Fichier 2.png
  src/images/Fichier 3.png
Labels: Ready for Validation

#9 Action jardin
  src/components/Action.js
  src/components/App.js
  src/components/Garden.js
  src/components/GardenInfos.js
  src/components/style/Action.scss
  src/components/style/Garden.scss
  src/components/style/GardenInfos.scss
  src/components/style/Login.scss
Labels: Ready for Validation

#13 Favorite
  .eslintrc.json
  src/components/ArticlesDetails.js
  src/components/Feed.js
  src/components/Navbar.js
  src/components/style/ArticlesDetails.scss
  src/components/style/Feed.scss
Labels: Ready for Validation

#14 finished first version of user page, but still have to check that gar…
  .eslintrc.json
  package-lock.json
  package.json
  src/components/Action.js
  src/components/App.js
  src/components/AvatarEdition.js
  src/components/Feed.js
  src/components/UserDetails.js
  src/components/UserEdition.js
  src/components/style/UserDetails.scss
  src/components/style/UserEdition.scss
  src/services/API.js
Labels: bug

#22 Dev
  src/components/Action.js
  src/components/App.js
  src/components/AvatarEdition.js
  src/components/FetchActionToZone.js
  src/components/Garden.js
  src/components/GardenInfos.js
  src/components/TimeSlot.js
  src/components/style/ArticlesDetails.scss
  src/components/style/Feed.scss
  src/components/style/Garden.scss
  src/components/style/GardenInfos.scss
  src/index.css
Labels: Ready for prod
